<HTML>
<head>
<title>Family News Analyzer</title>
<meta name="description" lang="de" content="A tool to sum up and analyse the famnews.">
<meta name="keywords" content="imperial conflict,family,news,analyzer,summary,php,MMOG,massive,multiplayer,online,game">
<link REL=STYLESHEET HREF="ic.css" TYPE="text/css">



</head>

<BODY>
<h3>silenz.org - online tools for <a href="http://www.imperialconflict.com/">Imperial Conflict</a></h3>
<hr>

<hr>
<a href="news.php">Family News Analyzer</a> - 
<a href="reports.jsp">Recent Reports Summarizer</a> - 
<a href="science.jsp">Science</a> - 
<hr>
	<h3>family news analyzer</h3>
	Open the family news page, hit CTRL+A on it, CTRL+C and paste it into the field below.<br>

	Then you may choose between a <u>General Summary</u> with several options or a <u>Conflict Summary</u><br>

	which only sums up attacks between families.<br>

	Have fun. 
	<p>

	<FORM method="POST" action="news.php">
	<TEXTAREA name="news" cols=50 rows=5>
	</TEXTAREA>
	<br>

	<br>

	<TABLE><TR>
	<TD valign=top style="border-right: 1px solid black;">
	<input checked type="radio" class=radio name="summary" value="general">General Summary<br>
	<div style="margin-left: 20px;">
	<input type="checkbox" class="checkbox" name="show[0]" checked>attacks<br>
	<input type="checkbox" class="checkbox" name="show[1]" checked>failed attacks<br>
	<input type="checkbox" class="checkbox" name="show[2]" checked>defeats<br>
	<input type="checkbox" class="checkbox" name="show[3]" checked>successful defense<br>
	<input type="checkbox" class="checkbox" name="show[4]" checked>exploration<br>
	<input type="checkbox" class="checkbox" name="show[5]" checked>intra fam swaps<br>
	<input type="checkbox" class="checkbox" name="show[6]" checked>aid shipments<br>
	<input type="checkbox" class="checkbox" name="show[7]" checked>missing planets<br>
	</div>
	</TD>
	
	<TD valign=top>
	<input type="radio" class=radio name="summary" value="conflict">Conflict Summary<br>
	<div style="margin-left: 20px;">
	<input type="radio" class=radio name="filter" checked>show all<br>
	<input type="radio" class=radio name="filter" value="top">show only top
	<select name="top">
		<option>1
		<option selected>3
		<option>5
		<option>10
	</select><br>
	<input type="radio" class=radio name="filter" value="fams">show families
	<div style="margin-left: 30px;">
	<input type="text" name="fam[0]" size=5 maxlength=4><br>
	<input type="text" name="fam[1]" size=5 maxlength=4><br>
	<input type="text" name="fam[2]" size=5 maxlength=4><br>
	</div>
	<br>
	</div>
	</TD>
	</TR>
	<TR><TD colspan=2>
	Enter average resource-prices below if you would like<br>
	a balance of the aid-shipments.<br>
	Iron:<input type="text" name="bp_iron" size=4 maxlength=5> 
	Endu:<input type="text" name="bp_endu" size=4 maxlength=5> 
	Food:<input type="text" name="bp_food" size=4 maxlength=5> 
	Octa:<input type="text" name="bp_octa" size=4 maxlength=5> 
	</TD></TR>
	</TABLE>
	<INPUT type="submit" class="submit" value="Format!">
	</FORM>
	<h3>family news summarizer</h3>
	Into the field below you can insert multiple reports generated by the formatter<br>
	above in order to summarize them.<br>
	If you have collected the reports for several years in your forum for example you can
	paste them in here and get all the years added together.	
	<br>

	
	<p>

	<FORM method="POST" action="newssum.php">
	<TEXTAREA name="news" cols=50 rows=5>
	</TEXTAREA>
	<br>

	<INPUT type="submit" class="submit" value="Format!">
	</FORM><hr>
<div align=center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<a href="imprint.php">imprint</a>
</div>